#!/usr/bin/env bash

set -euo pipefail

DOTFILES_PATH=$HOME/.dotfiles

echo "⚙️  Dotfiles"
echo "-------------"
echo
echo "Dotfiles is going to be installed in $DOTFILES_PATH"

git clone --depth 1 git@github.com:joseahernandez/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install
