#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?    install

docs::eval_help "$@"

# Install brew (https://brew.sh)
echo
log::note "Installing brew 🍺"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/jose.hernandez/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/jose.hernandez/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install framework zimfw for zsh
echo
log::note "Installing zimfw 💻"
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
export ZIM_HOME="${ZDOTDIR:-${HOME}}/.zim"

# Remove bash last login
touch "$HOME/.hushlogin"

echo
log::note "Installing macOS apps "
brew bundle --file="$DOTFILES_PATH/macOS/brew/Brewfile"

"$DOTFILES_PATH/bin/dot" self update

# Correct paths (so, we handle all with $PATH)
#sudo cp /etc/paths "$DOTFILES_PATH/backup/paths"
#sudo truncate -s 0 /etc/paths

# Fix error signing commits
gpg-agent --daemon || true
echo "pinentry-program /usr/local/bin/pinentry-mac" >> "$HOME/.gnupg/gpg-agent.conf"
killall gpg-agent || true

echo
log::note "Installing fonts ✍️"
# Install Fonts
cp "$DOTFILES_PATH"/fonts/*/*.ttf "$HOME/Library/Fonts"

# Install Powerline fonts
git clone https://github.com/powerline/fonts.git --depth=1 powerline_fonts
cd powerline_fonts
./install.sh
cd ..
rm -rf powerline_fonts

echo
log::note "Setting ZSH as the default shell 💻 "
chsh -s "$(command -v zsh)"

echo
log::warning "Remember to run 'dot shell zsh optimize'"

echo
log::success "Instalation success 🤘"
